### PR TITLE
Auth client

### PR DESCRIPTION
**Pull request by Medic1111**
ATTENTION: Fetch user controller on server is COMMENTED OUT for testing purposes.
Deletion of Client/Helpers
Using Proxy only
Creation of PROFILE: No style, basic structure, Fetch user Effect (by ID), nav will be added once Mock DB is Set to open Spec Post Modal.
PS: Testing is becoming increasingly difficult using Mock arr on client.... Probably good time to add mock entries on DB to ensure all flows well, and quicker. =)
GO TEAM!

### CODE REVIEW

**Review by Roupiye — CHANGES_REQUESTED** [review]
restore the user controller file in the server i will create a database seed so you can have data to test with

git restore -s development  app/server/controllers/users_controller.js
git add .
git commit -m "restore user controllers"
git push origin authClient

**Comment by Medic1111** [comment]
No need to restore Breno.... Yours is there as I said just commented.... Just uncomment and delete the 3 lines.

**Comment by Medic1111** [comment]
Remember I mentioned its for testing, and you will need that too in order to test what I just did

**Comment by Roupiye** [comment]
i will make a pr to this branch then to add the seeds so you dont need to hard code responses any more.

**Comment by Roupiye** [comment]
im fixing the main page so you use actual data from the server

**Review by Roupiye — APPROVED** [review]
with the seeds now its easier to get test data from the server.

**Comment by Roupiye** [comment]
to run the seeds is npx sequelize-cli db:seed:all
and to revert them is npx sequelize-cli db:seed:undo:all

**Pull request merged**
