### PR TITLE
START: To fix Home page per Data received from server

### PR DESCRIPTION
**Pull request by Medic1111**
Starting to fix the Home page to ensure it flows with the data of POSTS received by the server. Context will be created as soon as everything works again.

### CODE REVIEW

**Comment by Roupiye** [comment]
i was doing the exact same thing

**Comment by Medic1111** [comment]
Dont worry about it. To make things easier, I mentioned on the meeting last time we should do Data modeling for the posts to avoid things that are already built on the client from  breaking. So let's slow down and get ourselves situated again. And most importantly, on the same page. =)

**Comment by Roupiye** [comment]
the way ive set up the data response in the server it wont change much, we may add things like tags in the future but the data structure is the same.

**Comment by Medic1111** [comment]
Right... its just unfortunate that we didn't do a modeling together, so Now it added quite some work on the client, that was already done. lol. It is what it is... We can address that in the meeting. Im starting the context but there isn't much I can do until we figure the Model and are able to ensure they work together, and then everything else should flow nicely.
See you tonight. Merge when ready.

**Comment by TopRoupi** [comment]
looking at this pr 100% of what you did here i did too, you removed the data parsing from the fetch and used the server response data for the usestate, then you made the changes to the post item component to work it was doing before.

**Pull request merged**
